### PR TITLE
Adds routing authentication helpers

### PR DESCRIPTION
**Pull request by willcosgrove**
Decided to try implementing this to get familiar with Challah.  I noticed in a recent project that the sidekiq dashboard was not behind the authentication, just obfuscated behind a long token.  So I decided to add some route helpers to let you block certain routes if the user is not authenticated, or doesn't pass a certain requirement.

This will let you wrap routes in an authenticate block

``` ruby
authenticate User, ->(u) { u.admin? } do
  get '/admin/dashboard', to: 'restrictions#index'
end
```

Handy for mounted apps

``` ruby
authenticate Admin::User do
  mount Sidekiq::Web => '/admin/sidekiq'
end
```

When used without an explicit user model, will default to `Challah.user`

Using this would let us drop a bunch of custom `*Constraint` classes.

### CODE REVIEW

**Comment by courtsimas** [comment]
Well, we could definitely use this for boutique ...

**Comment by thewatts** [comment]
@willcosgrove this looks really good, man! Great work!

I am a little hesitant to add the `admin` boolean to the `User` class, as there is already a `role_id` field.
Could just be my limited exposure with using the gem though. 

Typically I've seen `Challah` used in two ways:

1. With two separate user classes, ex: `User` and `Admin::User` (in which case the `admin` boolean wouldn't apply, and would likely needed to be removed in a separate migration).

2. The `role_id` has been in heavy usage (such as in Ignite, where they have a ton of different user roles).

We do have an instance where we have an app (BeyondTheShock) that is using _both_ an `admin` boolean and a type of `role_id`, and it was a bit confusing when we went back into it to debug some stuff.

Just my 2 cents - ultimately it comes down to @jdtornow ;)

Either way, _stoked_ to have this routing functionality in `Challah`!

**Comment by jdtornow** [comment]
Thanks for sending this through @willcosgrove -- nice to have you contributing!

Agreed 100% with @thewatts. If we can use the existing `role_id` field, that would be great. Challah tries to not assume anything about implementation of what an admin is or anything to that effect, it is just simply a mechanism for authentication and storing user credentials. It is intentionally lean. The rest is up to your app :)

Also, would love to see if there is a way to add the `authenticate` method for routing help without opening up a Rails core class. There may not be a way to do this elegantly, but just throwing it out there as an idea.

**Comment by willcosgrove** [comment]
Oh my bad about the admin thing.  I was thinking that that was just a testing construct, I didn't realize it is a model that gets added to the host app.  Yeah no, definitely don't want to assume the User setup like that.

Same thing with the `Admin::User` in the example above.  I didn't realize it was working from a Challah created User record.  I was just diversifying the examples, showing that you could pass in any class that used Challah.

@jdtornow I'll check out alternatives for adding this to the Rails Routing Mapper.

**Comment by jdtornow** [comment]
No worries @willcosgrove -- this really has us thinking. @thewatts and I are chatting on other solutions as well :)

**Comment by willcosgrove** [comment]
Ok, I've removed the `authenticate` route helper, in favor of a `AuthenticatedRoutingConstraint` class.  I'm having trouble getting the tests to pass now though.  I'm not sure what's wrong with it, I thought I would push it up here and see if y'all could find anything obviously wrong with it.  It appears that the `request` object that is being passed in in the tests, do not have any `Challah::Session`s associated with it.  So the tests never see anyone as being signed in.  :disappointed:

**Comment by courtsimas** [comment]
What ever became of this?

**Comment by jdtornow** [comment]
@courtsimas I don't remember :)  I think we were debating internally a few different ways to do this without changing the core, but not sure where that netted out.

**Pull request closed without merging**
